import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header";
import Footer from "../components/footer";
import { AdvertsProvider } from "@/providers/adverts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdvertsProvider>
          <Header />
          <div className="px-2">{children}</div>
          <Footer />
        </AdvertsProvider>
      </body>
    </html>
  );
}
